version: '3.8'

services:
  review-bot-db:
    image: postgres:14.1-alpine
    container_name: review-bot-db
    restart: always
    environment:
      POSTGRES_DB: review_bot
      POSTGRES_USER: ${REVIEW_BOT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${REVIEW_BOT_DB_PASSWORD:-postgres}
    ports:
      - "5436:5432"
    logging:
      driver: "json-file" 
      options:
        max-size: 50m

  review-bot:
    image: nekromant322/review-bot:latest
    container_name: review-bot
    restart: unless-stopped
    environment:
      POSTGRES_HOST: review-bot-db
      POSTGRES_DB: review_bot
      TELEGRAM_BOT_DB_PORT: 5432
      POSTGRES_USER: ${REVIEW_BOT_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${REVIEW_BOT_DB_PASSWORD:-postgres}
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME:-MentoringReviewBot}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      LIFE_PAY_LOGIN: ${LIFE_PAY_LOGIN}
      LIFE_PAY_KEY: ${LIFE_PAY_KEY}
      OWNER_PASSWORD: ${OWNER_PASSWORD}
      CALL_PRICE: ${CALL_PRICE}
      TELEGRAM_BOT_PORT: ${TELEGRAM_BOT_PORT:-8080}
      TELEGRAM_BOT_PROFILE: ${TELEGRAM_BOT_PROFILE:-prod}
    ports:
      - "9100:8080"
    logging:
      driver: "json-file" 
      options:
        max-size: 50m
    depends_on:
      - review-bot-db

