bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
  userName: Marandyuk_Anatolii

server:
  port: ${PORT:8080}
  host: "https://mentoring-review-bot.herokuapp.com"

reminders:
  maxDaysWithoutReport: 3

pay-info:
  login: ${LIFE_PAY_LOGIN}
  apikey: ${LIFE_PAY_KEY}
  method: sbp

spring:
  datasource:
    password: ${PROD_POSTGRE_PASSWORD:root}
    username: ${PROD_POSTGRE_USERNAME:root}
    url: ${PROD_POSTGRE_URL:jdbc:postgresql://localhost:5432/bot}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

lombok:
  accessors:
    chain: true

schedulePeriod:
  start: 18
  end: 3