bot:
  name: ${TELEGRAM_BOT_NAME:MentoringReviewBot}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
  userName: ${OWNER_USER_NAME:Marandyuk_Anatolii}
  password: ${OWNER_PASSWORD}


server:
  port: 8080
  host: "https://overridetech.ru/review-bot"

reminders:
  maxDaysWithoutReport: 3

pay-info:
  login: ${LIFE_PAY_LOGIN:root}
  apikey: ${LIFE_PAY_KEY:root}
  method: sbp
price:
  resume-review: ${REVIEW_PRICE:5000}
  mentoring-subscription: ${MENTORING_PRICE:30000}

spring:
#  main:
#    allow-circular-references: true
  application:
    name: review-bot
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST}:${TELEGRAM_BOT_DB_PORT:5436}/review_bot
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: com.nekromant.telegram.utils.CustomDialectUtils # org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

lombok:
  accessors:
    chain: true

schedulePeriod:
  start: 15
  end: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.zalando.logbook: TRACE
